### ISSUE TITLE
not working with ios app

### ISSUE THREAD

**Issue by dhrutimehta** [MohamedAbd0/widgets_to_image#14]
error : [ERROR:flutter/lib/ui/painting/image_encoding.cc(210)] Could not convert raster image to PNG.

**Comment by JaspreetSingh04012001** [comment]
Yes please look into this issue

**Comment by MohamedAbd0** [comment]
can you shard the code with me?

**Comment by amankachhal99** [comment]
I am also facing similar kind of issue

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Unable to find RenderRepaintBoundary
#0      WidgetsToImageController2.capture.<anonymous closure> (package:aanandamfe/services/share_info/widgets_to_image_controller.dart:38:11)
#1      new Future.delayed.<anonymous closure> (dart:async/future.dart:423:39)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

  Future<Uint8List?> capture({
    double pixelRatio = 6,
  }) async {
    try {
      return await Future.delayed(Duration.zero, () async {
        RenderRepaintBoundary? boundary = containerKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;

        if (boundary == null) {
          throw Exception('Unable to find RenderRepaintBoundary');
        }

        final image = await boundary.toImage(pixelRatio: pixelRatio);
        final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
        final pngBytes = byteData?.buffer.asUint8List();
        return pngBytes;
      });
    } catch (e) {
      rethrow;
    }
  }

  static Future<void> shareWidgetByImage(Widget widget, String content) async {
    // WidgetsToImageController to access widget
    WidgetsToImageController2 controller = WidgetsToImageController2();
    // to save image bytes of widget
    Uint8List? bytes;
    WidgetsToImage2(
      controller: controller,
      child: widget,
    );
    // Ensure the capture is done after the widget is rendered
    WidgetsBinding.instance!.addPostFrameCallback((_) async {
      bytes = await controller.capture();
      if (bytes != null) {
        shareImageFromBytes(bytes!, content);
      } else {
        _logger.e('Failed to capture widget as image');
      }
    });
  }

**Comment by MohamedAbd0** [comment]
Hi @dhrutimehta @JaspreetSingh04012001 @amankachhal99,

Thanks for reporting this issue! The problems you're experiencing are related to widget lifecycle and timing issues that have been completely resolved in **v2.0.0**.

## 🐛 Root Cause Analysis

The errors you're seeing:
- `Could not convert raster image to PNG`
- `Unable to find RenderRepaintBoundary`

These occur because:
1. **Timing Issues**: Trying to capture before the widget is fully rendered
2. **Context Lifecycle**: RenderRepaintBoundary not being found due to widget disposal
3. **Missing Error Handling**: No proper validation of the render boundary state

## ✅ Solution: Upgrade to v2.0.0

These issues are **completely fixed** in the new version with:

### 1. **Robust Error Handling**
```dart
// v2.0.0 includes proper validation
final bytes = await controller.capturePng();
// Automatically handles boundary validation and timing
